"""create remindme table

Revision ID: 9995e103227e
Revises: 
Create Date: 2025-10-27 20:16:17.063900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9995e103227e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remindme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('days', sa.String(length=100), nullable=False),
    sa.Column('alert_sound', sa.String(length=50), nullable=False),
    sa.Column('alert_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remindme'))
    )
    op.create_index(op.f('ix_remindme_label'), 'remindme', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remindme_label'), table_name='remindme')
    op.drop_table('remindme')
    # ### end Alembic commands ###
