"""add alert_type

Revision ID: c77a0bd03952
Revises: bb4724f4e82d
Create Date: 2025-10-27 23:42:42.775255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77a0bd03952'
down_revision: Union[str, Sequence[str], None] = 'bb4724f4e82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remindme', sa.Column('alert_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remindme', 'alert_type')
    # ### end Alembic commands ###
