"""set active to True by default and index

Revision ID: dc6946700f53
Revises: 9995e103227e
Create Date: 2025-10-27 23:14:25.424877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6946700f53'
down_revision: Union[str, Sequence[str], None] = '9995e103227e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_remindme_active'), 'remindme', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remindme_active'), table_name='remindme')
    # ### end Alembic commands ###
