#: import utils kivy.utils
#: import Factory kivy.factory.Factory

<AddReminderItem>:
    label_input:label_input
    label_input_count:label_input_count
    selected_days:selected_days
    popup_alarm_check: popup_alarm_check
    sound_alarm_check: sound_alarm_check
    time_hours: time_hours
    time_minutes: time_minutes
    time_seconds: time_seconds
    submit: submit
    GridLayout:
        cols: 1
        row_default_height: '50dp'
        spacing: 10, 10
        padding: 5, 5
        GridLayout: # UI-1
            canvas.before:
                Color:
                    rgba: utils.get_color_from_hex('#4f4e4e')
                Rectangle:
                    pos: self.pos 
                    size: self.size
            cols: 2
            Label:
                text: 'Time'
            Label:
                text: 'Repeat'
        GridLayout: # UI-2
            cols: 2
            GridLayout: # UI-2-1
                rows: 2
                BoxLayout: # UI-2-1-1
                    orientation: 'horizontal'
                    TextInput:
                        id: time_hours
                        hint_text:'00'
                        size_hint_x: 0.5
                        on_text: 
                            root.verify_time_value(self, 23)
                            root.try_enable_submit()
                        multiline: False
                        on_text_validate: time_minutes.focus=True
                    TextInput:
                        id: time_minutes
                        hint_text:'00'
                        size_hint_x: 0.5
                        on_text: root.verify_time_value(self)
                        multiline: False
                        on_text_validate: time_seconds.focus=True
                    TextInput:
                        id: time_seconds
                        hint_text:'00'
                        size_hint_x: 0.5
                        on_text: root.verify_time_value(self)
                        multiline: False 
                        on_text_validate: label_input.focus=True
                BoxLayout: # UI-2-1-2
                    orientation: 'horizontal'
                    Label:  
                        text: 'hh'
                    Label:  
                        text: 'mm'
                    Label:  
                        text: 'ss'
            BoxLayout: # UI-2-2
                orientation: 'vertical'
                Button:
                    text: "days >"
                    background_color: (35/255, 36/255, 35/255, 1)
                    on_release: Factory.DaysPopup().open()
                DaysLabel:
                    id: selected_days
                    text: ''
                    on_text: root.try_enable_submit()
                    canvas.before:
                        Color: 
                            rgba: (35/255, 36/255, 35/255, 1)
                        Rectangle:
                            size: self.size 
                            pos: self.pos 
                    color: (247/255, 134/255, 126/255, 1) # color of the text
                    font_size: 18
        BoxLayout: # UI-3
            orientation: 'vertical'
            height: '80dp'
            size_hint_y: None
            GridLayout: # UI-3-1
                cols: 5
                canvas.before:
                    Color: 
                        rgba: utils.get_color_from_hex('#4f4e4e')
                    Rectangle:
                        size: self.size 
                        pos: self.pos 
                Label: 
                    text: 'Popup'
                    size_hint_x: 0.3
                CheckBox:
                    id: popup_alarm_check
                    active: False
                    on_active: root.try_enable_submit()
                    size_hint_x: 0.1
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label: 
                    text: 'Sound'
                    size_hint_x: 0.4
                CheckBox:
                    id: sound_alarm_check
                    active: True
                    on_active: root.try_enable_submit()
                    size_hint_x: 0.1
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.1
            GridLayout: # UI-3-2
                cols: 2
                height: '30dp'
                size_hint_y: None 
                Button: 
                    text: 'Select Sound >'
                    background_color: (35/255, 36/255, 35/255, 1)
                    size_hint_x: 0.4
                    font_size: 25
                    on_release: Factory.FilePickerPopup().open()
                SelectedSoundLabel:
                    text: 'No Sound Selected'
                    size_hint_x: 0.6
                    font_size: 18
                    markup: True
                    canvas.before:
                        Color:
                            rgba: (35/255, 36/255, 35/255, 1)
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                    color: utils.get_color_from_hex('#727070ff')
            GridLayout: # UI-3-3
                cols: 2
                height: '30dp'
                size_hint_y: None 
                Label:
                    text: 'Label'
                    size_hint_x: 0.3
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#4f4e4e')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                TextInput:
                    id: label_input
                    size_hint_x: 0.7
                    on_text: 
                        root.handle_label_input()
                        root.try_enable_submit()
        GridLayout: # UI-4
            rows: 2
            height: '90dp'
            size_hint_y: None 
            Label: 
                id: label_input_count
                text: '-27'
                height: '20dp'
                size_hint_y: None 
                halign: 'right'
                text_size: self.width * .8, None
                font_size: '13dp'
                markup: True
            GridLayout:
                cols: 2
                Button: 
                    text: 'Reset'
                    background_color: (252/255, 36/255, 8/255, 1)
                    on_release: root.reset()
                Button:
                    id: submit
                    text: 'Submit'
                    disabled: True 
                    background_color: (4/255, 204/255, 57/255, 1)
        Label: # UI-5
            text: ''
            canvas.before:
                Color:
                    rgba: (64/255, 62/255, 63/255, 1)
                Rectangle:
                    size: self.size 
                    pos: self.pos 
            color: (62/255, 92/255, 70/255, 1)
            font_size: 48
        Label: # UI-6
            text: ''
        
<DaysPopup>:
    auto_dismiss: True 
    title: 'Days'
    size_hint: 0.9, 0.7
    GridLayout:
        rows: 3
        spacing: 15
        padding: 15
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None 
            height: '20dp'
            canvas.before:
                Color:
                    rgba: utils.get_color_from_hex('#212121ff')
                Rectangle:
                    size: self.size 
                    pos: self.pos
            Label:
                text: 'Repeat'
                size_hint_x: 0.3
            CheckBox:
                active: False 
                size_hint_x: 0.1
                canvas.before:
                    Color:
                        rgba: utils.get_color_from_hex('#727070ff')
                    Rectangle:
                        size: self.size 
                        pos: self.pos
            Label:  
                text: ''
                size_hint_x: 0.6
        MDDivider:
            size_hint_x: .03
            theme_divider_color: 'Custom'
            color: utils.get_color_from_hex('#3d3c3cff')
            pos_hint: {'center_x': 0.5,'center_y': 0.5}
        GridLayout:
            rows: 7
            padding: 15
            spacing: 15
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Mon'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Mon')
                    on_active: root.days_popup_check(self.active, 'Mon')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Tue'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Tue')
                    on_active: root.days_popup_check(self.active, 'Tue')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Wed'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Wed')
                    on_active: root.days_popup_check(self.active, 'Wed')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Thur'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Thur')
                    on_active: root.days_popup_check(self.active, 'Thur')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Fri'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Fri')
                    on_active: root.days_popup_check(self.active, 'Fri')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Sat'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Sat')
                    on_active: root.days_popup_check(self.active, 'Sat')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            BoxLayout:
                orientation: 'horizontal'
                Label:
                    text: 'Sun'
                    size_hint_x: 0.6
                CheckBox:
                    size_hint_x: 0.1
                    active: root.restore_days_check('Sun')
                    on_active: root.days_popup_check(self.active, 'Sun')
                    canvas.before:
                        Color:
                            rgba: utils.get_color_from_hex('#aaaaaaff')
                        Rectangle:
                            size: self.size 
                            pos: self.pos
                Label:
                    text: ''
                    size_hint_x: 0.3
            
<FilePickerPopup>:
    file_chooser: file_chooser
    title: 'Select an Audio File'
    size_hint: 0.9, 0.9
    BoxLayout:
        orientation: 'vertical'
        FileChooserIconView:
            id: file_chooser
            filters: ['*.mp3', '*.wav', '*.ogg']
            path: root.get_last_path()
        Button:
            text: 'Select'
            size_hint_y: None 
            height: 50
            on_release: root.select_file()

            
